title: Siber Defense Club - Mount Si High School
description: Home of the MSHS Siber Defense Club
remote_theme: siberdefense/modernist@v0.2.1
plugins:
- jekyll-remote-theme
show_downloads: false
google_analytics: G-4ZM7GEW6GH
github:
- is_project_page: false
